name: debpkg 

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 13 * * 1'

jobs:
  build:
    name: build debpkg
    runs-on:  ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [aarch64-linux-gnu, arm-linux-gnueabihf]

    steps:
      - name: set up git repository
        uses: actions/checkout@v2

      - name: set up enviroment
        run: |
          sudo apt-get install libeigen3-dev libcppunit-dev
          sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          pip install psutil future

      - name: build orocos_kdl_package
        run: |
          ls
          chmod +x build.sh
          ./build.sh ${{matrix.compiler}}
          ls

      - name: upload debpkg to artifactory
        uses: actions/upload-artifact@v2
        with:
          name: debpkg
          path: ./*.deb
